# Generated by Django 2.0 on 2017-12-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiariosdiesel',
            name='actividad_productiva',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosdiesel',
            name='componente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosdiesel',
            name='folio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosdiesel',
            name='llave_unica',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosdiesel',
            name='npa_emb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosdiesel',
            name='programa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosdiesel',
            name='rnpa_emb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosdiesel',
            name='sexo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosdiesel',
            name='suma_litros_asignados',
            field=models.IntegerField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiariosgasolina',
            name='actividad_productiva',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosgasolina',
            name='componente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosgasolina',
            name='folio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosgasolina',
            name='llave_unica',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosgasolina',
            name='npa_emb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosgasolina',
            name='programa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosgasolina',
            name='rnpa_emb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosgasolina',
            name='sexo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiariosgasolina',
            name='suma_litros_asignados',
            field=models.IntegerField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
